---

#- name: 「ec2-user」を削除する
#  become: yes
#  user:
#    name: ec2-user
#    state: absent
#    remove: yes
- name: 動画エンコード用のディレクトリ作成
  become: yes
  file:
    path: /var/movie
    state: directory
    mode: 0777
#- name: ec2-userディレクトリ作成
#  become: yes
#  file:
#    path: /home/ec2-user/backup
#    owner: vagrant
#    group: vagrant
#    state: directory
#    mode: 0755
- name: composerディレクトリ作成
  become: yes
  file:
    path: /home/composer
    owner: vagrant
    group: vagrant
    state: directory
    mode: 0755
- name: ec2-userディレクトリにあるべきファイルのコピー
  copy:
    src: "{{item}}"
    dest: /home/ec2-user
    mode: 0777
  with_items:
    - minjs.sh
    - sass.sh
    - package.json
    - gulpfile.js
    - .babelrc
- name: package.jsonのシンボリックリンクを作成
  file:
    src: /home/ec2-user/package.json
    dest: /var/www/html/front-end/dev/package.json
    mode: 755
    state: link
- name: gulpfile.jsのシンボリックリンクを作成
  file:
    src: /home/ec2-user/gulpfile.js
    dest: /var/www/html/front-end/dev/gulpfile.js
    mode: 755
    state: link
- name: .babelrcのシンボリックリンクを作成
  file:
    src: /home/ec2-user/.babelrc
    dest: /var/www/html/front-end/dev/.babelrc
    mode: 755
    state: link
- name: phpunitをgit管理しているものへのsymlinkにする
  become: yes
  file:
    src: /var/www/html/phpunit/bin/phpunit-6.5.phar
    dest: /usr/bin/phpunit
    state: link
- name: 「.bashrc」をバックアップ
  copy: >
    remote_src=yes
    src=/home/vagrant/.bashrc
    dest=/home/vagrant/.bashrc.BAK
    owner=vagrant
    group=vagrant
- name: オリジナルの「.bashrc」を削除
  file:
    path: /home/vagrant/.bashrc
    state: absent
- name: /var/www/html/.bashrcへのシンボリックリンクを作成
  file:
    src: /var/www/html/.bashrc
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
    mode: 755
    state: link
- name: 「Too many open files」の設定の変更
  become: yes
  replace:
    path: /etc/systemd/system.conf
    regexp: '^#(DefaultLimitNOFILE|DefaultLimitNPROC)='
    replace: '\1=1006500'
#- name: 再起動
#  become: yes
#  reboot:
